<?php
/**
 * @file
 * Contains views API hooks for Flag weights module.
 */

/**
 * Implements hook_views_data().
 * Provide a field that can be used to sort a view.
 * @todo: The field itself gets exposed to views by the Entity/Views API;
 * we probably just need to add the sort handling here.
 */
//function flag_weights_views_data() {
//  $data = [];
//
//  $data['flagging']['weight'] = [
//    'title' => t('Weight'),
//    'help' => t('The flagging\'s weight.'),
//    'real field' => 'weight',
//    'field' => [
//      'id' => 'numeric',
////      'click sortable' => TRUE,
//    ],
//    'sort' => [
//      'handler' => 'views_handler_sort_flag_weights',
//    ],
//  ];
//
//  return $data;
//}

